# handlers/__init__.py

MENU, CHOOSE_AQUARIUM, \
ADD_AQUARIUM_NAME, ADD_AQUARIUM_TYPE, ADD_AQUARIUM_VOLUME, \
AQUARIUM_MENU, PARAM_CHOOSE, PARAM_VALUE, \
HISTORY_MENU, HISTORY_PERIOD, HISTORY_YEAR, HISTORY_MONTH, HISTORY_PAGINATE, \
CONFIRM_ADD_MEASUREMENT, CHART_PARAM, SETTINGS, EDIT_NAME, EDIT_VOLUME, EDIT_TYPE, CONFIRM_DELETE, SERVICE_MENU,\
ADD_SERVICE_STEP, DELETE_SERVICE_STEP, MARK_DONE_STEP, \
NOTES_MENU, NOTE_ADD, NOTE_EDIT, NOTE_DELETE_CONFIRM = range(28)